const cartes = [
  {
    photo: "./assets/photo_carte/photo_bastien.png",
    nom: "Bastien Domer",
    mail: "domer.bastien@gmail.com",
    softskills: ["Esprit d'équipe", "Détermination"],
    github: "https://github.com/BastienDmr",
    linkedin: "https://www.linkedin.com/in/bastien-domer-755045155/",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "Ann Dominique Thuillier",
    mail: "ann.dominique.d@gmail.com",
    softskills: ["", ""],
    github: "https://github.com/AnnDo33",
    linkedin: "https://www.linkedin.com/in/ann-dominique-t-694a7625/",
  },
  {
    photo: "./assets/photo_carte/photo_dylan.png",
    nom: "Dylan Robinaud",
    mail: "dylan.rbnd@gmail.com",
    softskills: ["Sens des responsabilités", "Aisance relationnelle"],
    github: "https://github.com/DylanRobinaud",
    linkedin: "https://www.linkedin.com/in/dylan-robinaud-648a03280/",
  },
  {
    photo: "./assets/photo_carte/photo_kathalina.png",
    nom: "Kathalina Sanchez",
    mail: "mkathalina.sanchez@gmail.com",
    softskills: ["Souci du détail", "Travail d'équipe"],
    github: "https://github.com/MariaKSanz",
    linkedin: "",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "Imanol Deleporte",
    mail: "imanol.deleporte@outlook.com",
    softskills: ["Ecoute active", "Esprit d'analyse"],
    github: "https://github.com/ITrogg",
    linkedin: "https://www.linkedin.com/in/imanol-deleporte-b2b28b304/",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "Nicolas Follain",
    mail: "follainnicolas8@gmail.com",
    softskills: ["Maturité professionnel", "Désir d'apprendre"],
    github: "",
    linkedin: "",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "",
    mail: "",
    softskills: ["", ""],
    github: "",
    linkedin: "",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "",
    mail: "",
    softskills: ["", ""],
    github: "",
    linkedin: "",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "",
    mail: "",
    softskills: ["", ""],
    github: "",
    linkedin: "",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "",
    mail: "",
    softskills: ["", ""],
    github: "",
    linkedin: "",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "",
    mail: "",
    softskills: ["", ""],
    github: "",
    linkedin: "",
  },
  {
    photo: "./assets/photo_carte/photo_.png",
    nom: "",
    mail: "",
    softskills: ["", ""],
    github: "",
    linkedin: "",
  },
];
